#!/bin/sh

input_bam=$1
prefix=$2
echo "#sort: chromosome-block" > $prefix.pairs
echo "#column1: readID" >> $prefix.pairs
echo "#column2: chr1" >> $prefix.pairs
echo "#column3: pos1" >> $prefix.pairs
echo "#column4: chr2" >> $prefix.pairs
echo "#column5: pos2" >> $prefix.pairs
echo "#column6: flag" >> $prefix.pairs ## will convert to strands later..
samtools view -X -F12 $input_bam | cut -f1,3,4,7,8,2 | sort -k2,2 -k4,4 -k3,3g -5,5g >> $prefix.bsorted.pairs
bgzip $prefix.bsorted.pairs
pairix $prefix.bsorted.pairs.gz


